Label odd numbered tests
zherczeg/sljit pull request #134
Opened 2022-11-04 19:05 UTC by matetokodi

2022-11-07 11:10 UTC, zherczeg commented
Please always squash your commits

2022-11-07 11:12 UTC, zherczeg requested changes
Good patch

2022-11-07 11:12 UTC, zherczeg commented on test_src/sljitTest.c
> +
No need these extra lines, the test becomes too long.

2022-11-07 11:12 UTC, zherczeg commented on test_src/sljitTest.c
> +	/*buf[7] */
You can write this in one line.

2022-11-10 13:25 UTC, zherczeg requested changes
Good patch. Not entirely clear when newlines are added or removed. Please fix the conflicts.

2022-11-10 14:32 UTC, matetokodi commented
Updated to keep the original spacing, except in test69, where I feel it is redundant with the addition of the comments

2022-11-11 11:22 UTC, zherczeg requested changes
I like that even return values are tagged with comments.

2022-11-11 11:22 UTC, zherczeg commented on test_src/sljitTest.c
> +	/*buf[0] */
Somehow from this point there is no space between the `*` and buf. Several similar cases below.

2022-11-11 11:22 UTC, zherczeg commented on test_src/sljitTest.c
> +	/*buf[4] and buf[5] */
The other patch used this format (sorry that was landed first):
`/* buf[4-5] */`
Please do this as well for consistency. I saw you also followed this format in some places.

2022-11-11 11:22 UTC, zherczeg commented on test_src/sljitTest.c
> +	/*Return vaue */
There is no space before `Return` word.

2022-11-11 13:12 UTC, zherczeg approved these changes
LGTM

2022-11-11 13:13 UTC, merged