Fix leaks
zherczeg/sljit pull request #234
Opened 2024-02-22 13:11 UTC by vorosl

2024-02-22 14:05 UTC, zherczeg requested changes

2024-02-22 14:05 UTC, zherczeg commented on test_src/sljitTestFloat.h
> +	struct sljit_compiler* compiler;
I would delete the `compiler = sljit_create_compiler(NULL, NULL);` below

2024-02-22 14:05 UTC, zherczeg commented on test_src/sljitTestFloat.h
> +	struct sljit_compiler* compiler;
Same here

2024-02-23 10:57 UTC, vorosl commented
Should I refactor all tests in this way?

2024-02-23 19:27 UTC, zherczeg commented
When reasonable.

2024-02-26 14:32 UTC, closed without merging